### ISSUE TITLE
Volume decreases and the sound degrades until it disappears.

### ISSUE THREAD

**Issue by 38github** [resonantdsp/SwankyAmp#21] opened 2020-07-16 22:46 UTC
I am using the latest version in Reaper 6.12c and after a while the power section lowers the volume as the time goes on and unwanted distortion appears. When lowering the drive on the output section the issue disappears and the volume increases but the issue reoccurs again after a while and won't go away.

**Comment by gmcgoldr** [comment] 2020-07-21 01:26
Hey, thanks for reporting this. I just fixed a bug that could have caused this sort of behaviour, but only after changing presets. If you get a chance to try out version 0.7.3, it might fix it. However what you're describing sounds a bit different, so I suspect it will require a bit more investigation.

**Comment by 38github** [comment] 2020-07-22 08:38
Thank you for your reply. I have now tried 0.8 and it has this issue too. It goes away after changing preset and going back to the problematic one.

**Comment by gmcgoldr** [comment] 2020-07-22 14:14
Alright, I will definitely look into that. Could you help me understand: does the issue only occur when the power amp drive is high? Is there a particular preset or parameter configuration for which it happens? How long does it take to go from the normal to the quieter distorted signal? Thanks.

**Comment by 38github** [comment] 2020-07-23 09:55
I had to make a loop that played almost thirty minutes because it started happening after about seven or eight and then after that continues to degrade and lower the volume. I can't say yet for sure if it is the power amp's fault so I would then need to do another test.

Here is the waveform, screenshot of settings and the sound sample.

![swanky_amp_08](https://user-images.githubusercontent.com/18294149/88273701-e1b69e80-ccda-11ea-98c0-d0b23647309e.png)

![swanky_amp_08_waveform](https://user-images.githubusercontent.com/18294149/88273723-e67b5280-ccda-11ea-9caf-ff3e84641727.png)

Opus audio sample, length 26:39. https://easyupload.io/nupyql

**Comment by 38github** [comment] 2020-07-23 10:38
Here is using the preset Pre Drive but the power amp drive is set to zero.

![swanky_amp_08_sound_sample_pre_drive_no_power_amp_drive_waveform](https://user-images.githubusercontent.com/18294149/88277551-39f09f00-cce1-11ea-9ef3-cf16aa11e472.png)

Opus audio sample, length 30:44. https://easyupload.io/mxygpt

**Comment by 38github** [comment] 2020-07-23 10:55
I changed the title of the issue since a preset with no power amp drive behaved the same as one with.

**Comment by gmcgoldr** [comment] 2020-07-25 21:17
Thanks for digging around, I know that takes a lot of time. The information is really useful, I think I've got the issue tracked down. I'll get a fix out as top priority.

**Comment by 38github** [comment] 2020-07-25 21:21
No problem att all. I am glad that I can help and seeing you doing this for free, me helping out is the last I can do.

Jul 25, 2020, 23:17 by notifications@github.com:

**Comment by gmcgoldr** [comment] 2020-07-27 17:21
Thanks again for helping me track this one down. It turns out the low pass filtering in the pre-amp was the root cause of the issue. Hopefully it will be fixed now.

**Closed by gmcgoldr** 2020-07-27 17:21 UTC

**Comment by 38github** [comment] 2020-07-28 12:24
No problem at all!

Jul 27, 2020, 19:21 by notifications@github.com:
